#!/usr/bin/env python
"""Show or save a posterior MCMC diagnostic figure."""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from shape_flow.utils import ConfigOption, merge_config


LOGGER = logging.getLogger("shape_flow.show_mcmc_figure")
DEFAULT_CONFIG = ROOT / "configs" / "sample_shape_posterior.ini"
CONFIG_OPTIONS = (
    ConfigOption("input", "paths", "output", "path"),
    ConfigOption("data", "paths", "data", "path"),
    ConfigOption("index", "observation", "index", "int", 0),
)


def configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot posterior samples generated by sample_shape_posterior.py."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="Existing sampler INI file. Defaults to configs/sample_shape_posterior.ini.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Posterior .npz file. Defaults to [paths] output from --config.",
    )
    parser.add_argument("--savefig", type=Path, help="Optional output figure path.")
    parser.add_argument(
        "--chain-savefig",
        type=Path,
        help="Optional output path for the separate chain figure.",
    )
    parser.add_argument(
        "--data",
        type=Path,
        help="Structured .npy data file used to read truth e1_t/e2_t.",
    )
    parser.add_argument("--index", type=int, help="Row index used to read truth.")
    parser.add_argument(
        "--show",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Show the figure interactively. Defaults to true when --savefig is absent.",
    )
    parser.add_argument("--dpi", type=int, default=150)
    parser.add_argument("--max-points", type=int, default=5000)
    parser.add_argument("--truth", type=float, nargs=2, help="Optional true e1 e2.")
    parser.add_argument("--title", default="MCMC posterior contour")

    args = merge_config(parser.parse_args(), CONFIG_OPTIONS)
    if args.input is None:
        raise ValueError("Provide --input or [paths] output in the existing config")
    if args.dpi < 1:
        raise ValueError("dpi must be positive")
    if args.max_points < 1:
        raise ValueError("max_points must be positive")
    if args.show is None:
        args.show = args.savefig is None and args.chain_savefig is None
    if args.chain_savefig is None and args.savefig is not None:
        args.chain_savefig = chain_figure_path(args.savefig)
    return args


def chain_figure_path(path: Path) -> Path:
    suffix = path.suffix or ".png"
    return path.with_name(f"{path.stem}_chain{suffix}")


def load_posterior_file(path: Path) -> SimpleNamespace:
    with np.load(path, allow_pickle=False) as data:
        if "samples" not in data.files:
            raise KeyError(f"{path} is missing the required 'samples' array")
        samples = np.asarray(data["samples"], dtype=np.float64)
        if samples.ndim != 2 or samples.shape[1] != 2:
            raise ValueError(f"samples must have shape (N, 2), got {samples.shape}")

        return SimpleNamespace(
            samples=samples,
            log_prob=_optional_array(data, "log_prob"),
            chain=_optional_array(data, "chain"),
            log_prob_chain=_optional_array(data, "log_prob_chain"),
            initial_state=_optional_array(data, "initial_state"),
            e_meas=_optional_array(data, "e_meas"),
            e_true=_optional_array(data, "e_true"),
            ncall=_optional_int(data, "ncall"),
            efficiency=_optional_float(data, "efficiency"),
        )


def resolve_truth(args: argparse.Namespace, plot_data: Any) -> np.ndarray | None:
    if args.truth is not None:
        return np.asarray(args.truth, dtype=np.float64)
    if args.data is not None:
        return load_truth_from_data_file(args.data, args.index)
    if plot_data.e_true is not None:
        truth = np.asarray(plot_data.e_true, dtype=np.float64)
        if truth.shape == (2,):
            return truth
    return None


def load_truth_from_data_file(path: Path, index: int) -> np.ndarray:
    loaded = np.load(path, allow_pickle=False)
    try:
        if isinstance(loaded, np.lib.npyio.NpzFile):
            if "e_true" in loaded.files:
                return np.asarray(loaded["e_true"][index], dtype=np.float64)
            missing = {"e1_t", "e2_t"} - set(loaded.files)
            if missing:
                raise KeyError(f"{path} is missing truth arrays: {sorted(missing)}")
            return np.asarray(
                [loaded["e1_t"][index], loaded["e2_t"][index]],
                dtype=np.float64,
            )

        if loaded.dtype.names is None:
            raise ValueError(f"{path} must be a structured array with e1_t/e2_t")
        missing = {"e1_t", "e2_t"} - set(loaded.dtype.names)
        if missing:
            raise KeyError(f"{path} is missing truth fields: {sorted(missing)}")
        return np.asarray(
            [loaded["e1_t"][index], loaded["e2_t"][index]],
            dtype=np.float64,
        )
    finally:
        close = getattr(loaded, "close", None)
        if close is not None:
            close()


def make_contour_figure(
    plot_data: Any,
    *,
    max_points: int,
    title: str,
    truth: np.ndarray | None,
    show: bool,
):
    plt = import_pyplot(show=show)
    patch_matplotlib_pandas_indexing()
    import zeus

    samples = select_plot_points(plot_data.samples, max_points=max_points)
    fig, axes = zeus.cornerplot(
        samples,
        labels=[r"$e_{1,t}$", r"$e_{2,t}$"],
        truth=truth,
        size=(8, 8),
    )
    fig.suptitle(title)
    if truth is not None:
        axes[1, 0].scatter(
            truth[0],
            truth[1],
            color="black",
            marker="x",
            s=80,
            linewidth=1.5,
            zorder=10,
            label="truth",
        )
        axes[1, 0].legend(loc="best")
    return fig


def patch_matplotlib_pandas_indexing() -> None:
    """Keep Zeus' seaborn-based cornerplot working with newer pandas."""

    import matplotlib.axes._base as axes_base
    import matplotlib.cbook as cbook

    original = cbook._check_1d
    if getattr(original, "_shape_flow_patched", False):
        return

    def check_1d(values):
        if hasattr(values, "to_numpy"):
            values = values.to_numpy()
        return original(values)

    check_1d._shape_flow_patched = True
    cbook._check_1d = check_1d
    axes_base._check_1d = check_1d


def make_chain_figure(
    plot_data: Any,
    *,
    title: str,
    show: bool,
):
    plt = import_pyplot(show=show)
    fig, axes = plt.subplots(2, 1, figsize=(10, 6), sharex=True, constrained_layout=True)
    chain = plot_data.chain
    if chain is None:
        axes[0].text(0.5, 0.5, "chain unavailable", ha="center", va="center")
        axes[1].text(0.5, 0.5, "chain unavailable", ha="center", va="center")
        for ax in axes:
            ax.set_axis_off()
        return fig

    values = np.asarray(chain, dtype=np.float64)
    if values.ndim != 3 or values.shape[2] != 2:
        axes[0].text(0.5, 0.5, "chain shape unsupported", ha="center", va="center")
        axes[1].text(0.5, 0.5, "chain shape unsupported", ha="center", va="center")
        for ax in axes:
            ax.set_axis_off()
        return fig

    plot_chain_component(axes[0], values[:, :, 0], label=r"$e_{1,t}$")
    plot_chain_component(axes[1], values[:, :, 1], label=r"$e_{2,t}$")
    axes[1].set_xlabel("step")
    fig.suptitle(title)
    return fig


def import_pyplot(*, show: bool):
    try:
        import matplotlib

        if not show:
            matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "matplotlib is required for plotting. Install the demo extras with "
            "`python -m pip install -e '.[demo]'`."
        ) from exc
    return plt


def select_plot_points(samples: np.ndarray, *, max_points: int) -> np.ndarray:
    if samples.shape[0] <= max_points:
        return samples
    indices = np.linspace(0, samples.shape[0] - 1, max_points, dtype=int)
    return samples[indices]


def plot_chain_component(ax, values: np.ndarray, *, label: str) -> None:
    steps = np.arange(values.shape[0])
    for walker in range(values.shape[1]):
        ax.plot(steps, values[:, walker], color="tab:blue", alpha=0.12, linewidth=0.8)
    ax.plot(steps, values.mean(axis=1), color="black", linewidth=1.6, label="mean")
    ax.set_xlabel("step")
    ax.set_ylabel(label)
    ax.legend(loc="best")


def _optional_array(data: np.lib.npyio.NpzFile, name: str) -> np.ndarray | None:
    if name not in data.files:
        return None
    return np.asarray(data[name])


def _optional_int(data: np.lib.npyio.NpzFile, name: str) -> int | None:
    values = _optional_array(data, name)
    if values is None:
        return None
    return int(np.asarray(values).reshape(-1)[0])


def _optional_float(data: np.lib.npyio.NpzFile, name: str) -> float | None:
    values = _optional_array(data, name)
    if values is None:
        return None
    return float(np.asarray(values).reshape(-1)[0])


def main() -> None:
    args = parse_args()
    configure_logging()
    LOGGER.info("stage=configuration_loaded")
    LOGGER.info("stage=posterior_loading path=%s", args.input)
    plot_data = load_posterior_file(args.input)

    truth = resolve_truth(args, plot_data)
    if truth is not None:
        LOGGER.info("stage=truth_loaded e1_t=%.6f e2_t=%.6f", truth[0], truth[1])
    else:
        LOGGER.info("stage=truth_unavailable")

    LOGGER.info("stage=contour_building samples=%d", plot_data.samples.shape[0])
    contour_fig = make_contour_figure(
        plot_data,
        max_points=args.max_points,
        title=args.title,
        truth=truth,
        show=args.show,
    )
    LOGGER.info("stage=chain_building")
    chain_fig = make_chain_figure(
        plot_data,
        title="MCMC chain",
        show=args.show,
    )

    if args.savefig is not None:
        args.savefig.parent.mkdir(parents=True, exist_ok=True)
        contour_fig.savefig(args.savefig, dpi=args.dpi)
        LOGGER.info("stage=contour_saved path=%s", args.savefig)
    if args.chain_savefig is not None:
        args.chain_savefig.parent.mkdir(parents=True, exist_ok=True)
        chain_fig.savefig(args.chain_savefig, dpi=args.dpi)
        LOGGER.info("stage=chain_saved path=%s", args.chain_savefig)
    if args.show:
        LOGGER.info("stage=figures_show")
        import_pyplot(show=True).show()


if __name__ == "__main__":
    main()
