#!/usr/bin/env python
"""Show or save a posterior MCMC diagnostic figure."""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from shape_flow.utils import ConfigOption, merge_config


LOGGER = logging.getLogger("shape_flow.show_mcmc_figure")
DEFAULT_CONFIG = ROOT / "configs" / "sample_shape_posterior.ini"
CONFIG_OPTIONS = (
    ConfigOption("input", "paths", "output", "path"),
)


def configure_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot posterior samples generated by sample_shape_posterior.py."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="Existing sampler INI file. Defaults to configs/sample_shape_posterior.ini.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        help="Posterior .npz file. Defaults to [paths] output from --config.",
    )
    parser.add_argument("--savefig", type=Path, help="Optional output figure path.")
    parser.add_argument(
        "--show",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Show the figure interactively. Defaults to true when --savefig is absent.",
    )
    parser.add_argument("--bins", type=int, default=40)
    parser.add_argument("--dpi", type=int, default=150)
    parser.add_argument("--max-points", type=int, default=5000)
    parser.add_argument("--truth", type=float, nargs=2, help="Optional true e1 e2.")
    parser.add_argument("--title", default="MCMC posterior samples")

    args = merge_config(parser.parse_args(), CONFIG_OPTIONS)
    if args.input is None:
        raise ValueError("Provide --input or [paths] output in the existing config")
    if args.bins < 1:
        raise ValueError("bins must be positive")
    if args.dpi < 1:
        raise ValueError("dpi must be positive")
    if args.max_points < 1:
        raise ValueError("max_points must be positive")
    if args.show is None:
        args.show = args.savefig is None
    return args


def load_posterior_file(path: Path) -> SimpleNamespace:
    with np.load(path, allow_pickle=False) as data:
        if "samples" not in data.files:
            raise KeyError(f"{path} is missing the required 'samples' array")
        samples = np.asarray(data["samples"], dtype=np.float64)
        if samples.ndim != 2 or samples.shape[1] != 2:
            raise ValueError(f"samples must have shape (N, 2), got {samples.shape}")

        return SimpleNamespace(
            samples=samples,
            log_prob=_optional_array(data, "log_prob"),
            chain=_optional_array(data, "chain"),
            log_prob_chain=_optional_array(data, "log_prob_chain"),
            initial_state=_optional_array(data, "initial_state"),
            e_meas=_optional_array(data, "e_meas"),
            ncall=_optional_int(data, "ncall"),
            efficiency=_optional_float(data, "efficiency"),
        )


def make_figure(
    plot_data: Any,
    *,
    bins: int,
    max_points: int,
    title: str,
    truth: np.ndarray | None,
    show: bool,
):
    plt = import_pyplot(show=show)
    samples = plot_data.samples
    plotted = select_plot_points(samples, max_points=max_points)

    fig, axes = plt.subplots(2, 2, figsize=(10, 8), constrained_layout=True)
    ax_joint, ax_hist, ax_trace, ax_info = axes.ravel()

    hist = ax_joint.hist2d(plotted[:, 0], plotted[:, 1], bins=bins, cmap="viridis")
    fig.colorbar(hist[3], ax=ax_joint, label="count")
    mean = samples.mean(axis=0)
    ax_joint.scatter(mean[0], mean[1], color="white", edgecolor="black", label="mean")
    if plot_data.e_meas is not None and plot_data.e_meas.shape == (2,):
        ax_joint.scatter(
            plot_data.e_meas[0],
            plot_data.e_meas[1],
            color="tab:red",
            marker="+",
            s=80,
            label="measured",
        )
    if truth is not None:
        ax_joint.scatter(
            truth[0],
            truth[1],
            color="black",
            marker="x",
            s=70,
            label="truth",
        )
    ax_joint.set_xlabel("intrinsic e1")
    ax_joint.set_ylabel("intrinsic e2")
    ax_joint.set_title(title)
    ax_joint.set_aspect("equal", adjustable="box")
    ax_joint.legend(loc="best")

    ax_hist.hist(samples[:, 0], bins=bins, alpha=0.65, label="e1")
    ax_hist.hist(samples[:, 1], bins=bins, alpha=0.65, label="e2")
    ax_hist.axvline(mean[0], color="tab:blue", linewidth=1)
    ax_hist.axvline(mean[1], color="tab:orange", linewidth=1)
    ax_hist.set_xlabel("intrinsic shape")
    ax_hist.set_ylabel("count")
    ax_hist.set_title("Marginal samples")
    ax_hist.legend(loc="best")

    plot_trace(ax_trace, plot_data.chain)
    write_summary(ax_info, plot_data)
    return fig


def import_pyplot(*, show: bool):
    try:
        import matplotlib

        if not show:
            matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "matplotlib is required for plotting. Install the demo extras with "
            "`python -m pip install -e '.[demo]'`."
        ) from exc
    return plt


def select_plot_points(samples: np.ndarray, *, max_points: int) -> np.ndarray:
    if samples.shape[0] <= max_points:
        return samples
    indices = np.linspace(0, samples.shape[0] - 1, max_points, dtype=int)
    return samples[indices]


def plot_trace(ax, chain: np.ndarray | None) -> None:
    if chain is None:
        ax.text(0.5, 0.5, "chain unavailable", ha="center", va="center")
        ax.set_axis_off()
        return
    values = np.asarray(chain, dtype=np.float64)
    if values.ndim != 3 or values.shape[2] != 2:
        ax.text(0.5, 0.5, "chain shape unsupported", ha="center", va="center")
        ax.set_axis_off()
        return
    mean_trace = values.mean(axis=1)
    ax.plot(mean_trace[:, 0], label="mean e1")
    ax.plot(mean_trace[:, 1], label="mean e2")
    ax.set_xlabel("step")
    ax.set_ylabel("ensemble mean")
    ax.set_title("Trace")
    ax.legend(loc="best")


def write_summary(ax, plot_data: Any) -> None:
    samples = plot_data.samples
    mean = samples.mean(axis=0)
    std = samples.std(axis=0)
    lines = [
        f"samples: {samples.shape[0]}",
        f"mean e1: {mean[0]:.5f}",
        f"mean e2: {mean[1]:.5f}",
        f"std e1: {std[0]:.5f}",
        f"std e2: {std[1]:.5f}",
    ]
    if plot_data.ncall is not None:
        lines.append(f"ncall: {plot_data.ncall}")
    if plot_data.efficiency is not None and np.isfinite(plot_data.efficiency):
        lines.append(f"efficiency: {plot_data.efficiency:.5f}")
    if plot_data.log_prob is not None:
        log_prob = np.asarray(plot_data.log_prob, dtype=np.float64)
        lines.append(f"max log prob: {np.nanmax(log_prob):.5f}")

    ax.text(0.02, 0.98, "\n".join(lines), va="top", family="monospace")
    ax.set_axis_off()
    ax.set_title("Summary")


def _optional_array(data: np.lib.npyio.NpzFile, name: str) -> np.ndarray | None:
    if name not in data.files:
        return None
    return np.asarray(data[name])


def _optional_int(data: np.lib.npyio.NpzFile, name: str) -> int | None:
    values = _optional_array(data, name)
    if values is None:
        return None
    return int(np.asarray(values).reshape(-1)[0])


def _optional_float(data: np.lib.npyio.NpzFile, name: str) -> float | None:
    values = _optional_array(data, name)
    if values is None:
        return None
    return float(np.asarray(values).reshape(-1)[0])


def main() -> None:
    args = parse_args()
    configure_logging()
    LOGGER.info("stage=configuration_loaded")
    LOGGER.info("stage=posterior_loading path=%s", args.input)
    plot_data = load_posterior_file(args.input)

    truth = None if args.truth is None else np.asarray(args.truth, dtype=np.float64)
    LOGGER.info("stage=figure_building samples=%d", plot_data.samples.shape[0])
    fig = make_figure(
        plot_data,
        bins=args.bins,
        max_points=args.max_points,
        title=args.title,
        truth=truth,
        show=args.show,
    )

    if args.savefig is not None:
        args.savefig.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.savefig, dpi=args.dpi)
        LOGGER.info("stage=figure_saved path=%s", args.savefig)
    if args.show:
        LOGGER.info("stage=figure_show")
        import_pyplot(show=True).show()


if __name__ == "__main__":
    main()
